version: '3.11'



services:
  bot:
    build: .
    restart: always
    container_name: pg_con2
    depends_on:
      - pg


  pg:
    image: postgres:alpine
    restart: always
    container_name: pg_con1
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: